name = "next-pyon"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next"

[vars]
NEXT_PUBLIC_API_URL = "https://next-pyon.pages.dev"
# Google Workspace OAuth configurations will be added here

[[d1_databases]]
binding = "DB"
database_name = "next-pyon-prod"
database_id = "0968da63-5c19-4b65-8f38-fb577357c47d"
migrations_dir = "../prisma/migrations"

[env.preview]
[[env.preview.d1_databases]]
binding = "DB"
database_name = "next-pyon-stage"
database_id = "54b0218d-ab55-4c41-8a57-a08ffc14d038"
migrations_dir = "../prisma/migrations"

[env.preview.vars]
NEXT_PUBLIC_API_URL = "https://next-pyon.pages.dev"
